from typing import Any

class Queries:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def add_queries(self, queries: Any) -> None: ...
    def add_child_queries(self, child_name: str, child_queries: "Queries") -> None: ...
