sonar.host.url=https://sonarcloud.io
sonar.organization=orshanski
sonar.projectKey=Orshanski_librarium-py

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests

sonar.python.version=3.11,3.12,3.13

sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**,**/dist/**,**/build/**,**/data/**,**/coverage/**,**/*.min.js,frontend/src/vendor/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.scm.provider=git
